spring.application.name=demo

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/fichiers_db
spring.datasource.username=adminbdd
spring.datasource.password=mdp
spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/gestion-fichiers