spring.application.name=bff

server.port=8081

spring.security.oauth2.client.registration.keycloak.client-id=bff-client
spring.security.oauth2.client.registration.keycloak.client-secret=wwrekwb225ctb5UBW6xUkryGR4mtIGdl
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/gestion-fichiers